[package]
name = "rusty-turing-machine"
version = "0.1.0"
authors = ["functional-tim <tim.gravert@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
